work pls

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,7 +12,7 @@ jobs:
     outputs:
       self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
     env:
-      CI: 'true'
+      CI: "true"
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -34,14 +34,12 @@ jobs:
         with:
           name: .repo.patch
           path: .repo.patch
-      - name: Add mutated files
+      - name: Fail build on mutation
         if: steps.self_mutation.outputs.self_mutation_happened
         run: |-
-          git config user.email "adriangabardo@gmail.com"
-          git config user.name "Adrian Gabardo"
-          git add .
-          git commit -m "[skip ci] mutated files"
-          git push
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat .repo.patch
+          exit 1
       - name: Upload artifact
         uses: actions/upload-artifact@v2.1.1
         with:
@@ -82,7 +80,7 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     permissions: {}
-    if: '! needs.build.outputs.self_mutation_happened'
+    if: "! needs.build.outputs.self_mutation_happened"
     steps:
       - uses: actions/setup-node@v2
         with:
@@ -104,7 +102,7 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     permissions: {}
-    if: '! needs.build.outputs.self_mutation_happened'
+    if: "! needs.build.outputs.self_mutation_happened"
     steps:
       - uses: actions/setup-java@v2
         with:
